// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_gear_png);    // assets/gear.png
LV_IMG_DECLARE(
    ui_img_mode_heat_64dp_1f1f1f_fill0_wght400_grad0_opsz48_png);    // assets/mode_heat_64dp_1F1F1F_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(ui_img_firewatch_480x480_png);    // assets/firewatch_480x480.png

// FONTS
LV_FONT_DECLARE(ui_font_gear);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
