// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TemperatureSlider = NULL;
lv_obj_t * ui_TemperstureLabel = NULL;
lv_obj_t * ui_DecreaseTemperatureButton = NULL;
lv_obj_t * ui_DecreaseTemperatureLabel = NULL;
lv_obj_t * ui_IncreaseTemperatureButton = NULL;
lv_obj_t * ui_IncreaseTemperatureLabel = NULL;
lv_obj_t * ui_TabViewPanel = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_SettingsButton = NULL;
lv_obj_t * ui_SettingsImg = NULL;
lv_obj_t * ui_HeatImg = NULL;
lv_obj_t * ui_CurrentTemperatureLabel = NULL;
lv_obj_t * ui_CurrentTemperatureValueLabel = NULL;
// event funtions
void ui_event_TemperatureSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_TemperstureLabel, target, "", "°");
    }
}

void ui_event_DecreaseTemperatureButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_arc_increment(ui_TemperatureSlider, -1);
    }
}

void ui_event_IncreaseTemperatureButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_arc_increment(ui_TemperatureSlider, 1);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_SettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TemperatureSlider = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_TemperatureSlider, 300);
    lv_obj_set_height(ui_TemperatureSlider, 300);
    lv_obj_set_x(ui_TemperatureSlider, 5);
    lv_obj_set_y(ui_TemperatureSlider, -65);
    lv_obj_set_align(ui_TemperatureSlider, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_TemperatureSlider, 50);
    lv_obj_set_style_radius(ui_TemperatureSlider, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TemperatureSlider, lv_color_hex(0x1A2026), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TemperatureSlider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TemperatureSlider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TemperatureSlider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TemperatureSlider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_TemperatureSlider, lv_color_hex(0x394C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TemperatureSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TemperatureSlider, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_TemperatureSlider, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_TemperstureLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TemperstureLabel, 150);
    lv_obj_set_height(ui_TemperstureLabel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_TemperstureLabel, 4);
    lv_obj_set_y(ui_TemperstureLabel, -69);
    lv_obj_set_align(ui_TemperstureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperstureLabel, "0");
    lv_obj_set_style_text_align(ui_TemperstureLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperstureLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DecreaseTemperatureButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_DecreaseTemperatureButton, 50);
    lv_obj_set_height(ui_DecreaseTemperatureButton, 50);
    lv_obj_set_x(ui_DecreaseTemperatureButton, -54);
    lv_obj_set_y(ui_DecreaseTemperatureButton, 60);
    lv_obj_set_align(ui_DecreaseTemperatureButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DecreaseTemperatureButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DecreaseTemperatureButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DecreaseTemperatureButton, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DecreaseTemperatureButton, lv_color_hex(0x394C4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DecreaseTemperatureButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DecreaseTemperatureLabel = lv_label_create(ui_DecreaseTemperatureButton);
    lv_obj_set_width(ui_DecreaseTemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DecreaseTemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DecreaseTemperatureLabel, 0);
    lv_obj_set_y(ui_DecreaseTemperatureLabel, -3);
    lv_obj_set_align(ui_DecreaseTemperatureLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DecreaseTemperatureLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DecreaseTemperatureLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_DecreaseTemperatureLabel, "-");
    lv_obj_set_style_text_font(ui_DecreaseTemperatureLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IncreaseTemperatureButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_IncreaseTemperatureButton, 50);
    lv_obj_set_height(ui_IncreaseTemperatureButton, 50);
    lv_obj_set_x(ui_IncreaseTemperatureButton, 64);
    lv_obj_set_y(ui_IncreaseTemperatureButton, 60);
    lv_obj_set_align(ui_IncreaseTemperatureButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IncreaseTemperatureButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IncreaseTemperatureButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IncreaseTemperatureButton, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IncreaseTemperatureButton, lv_color_hex(0x394C4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IncreaseTemperatureButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IncreaseTemperatureLabel = lv_label_create(ui_IncreaseTemperatureButton);
    lv_obj_set_width(ui_IncreaseTemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IncreaseTemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IncreaseTemperatureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IncreaseTemperatureLabel, "+");
    lv_obj_set_style_text_font(ui_IncreaseTemperatureLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabViewPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_TabViewPanel, 70);
    lv_obj_set_width(ui_TabViewPanel, lv_pct(100));
    lv_obj_set_align(ui_TabViewPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_TabViewPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TabViewPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TabViewPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TabViewPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TabViewPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TabViewPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TabViewPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TabViewPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_TabViewPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TabViewPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_TabViewPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TabViewPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TabViewPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TabViewPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_TabViewPanel);
    lv_obj_set_height(ui_Button4, lv_pct(100));
    lv_obj_set_flex_grow(ui_Button4, 1);
    lv_obj_set_x(ui_Button4, 96);
    lv_obj_set_y(ui_Button4, -118);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x1A2026), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_TabViewPanel);
    lv_obj_set_height(ui_Button5, lv_pct(100));
    lv_obj_set_flex_grow(ui_Button5, 1);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x1A2026), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButton = lv_btn_create(ui_TabViewPanel);
    lv_obj_set_height(ui_SettingsButton, lv_pct(100));
    lv_obj_set_flex_grow(ui_SettingsButton, 1);
    lv_obj_set_align(ui_SettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsButton, lv_color_hex(0x1A2026), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SettingsButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingsButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SettingsButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SettingsButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsImg = lv_img_create(ui_SettingsButton);
    lv_img_set_src(ui_SettingsImg, &ui_img_gear_png);
    lv_obj_set_width(ui_SettingsImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingsImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeatImg = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_HeatImg, &ui_img_mode_heat_64dp_1f1f1f_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_HeatImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeatImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeatImg, 5);
    lv_obj_set_y(ui_HeatImg, 23);
    lv_obj_set_align(ui_HeatImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HeatImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HeatImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentTemperatureLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CurrentTemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentTemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentTemperatureLabel, -82);
    lv_obj_set_y(ui_CurrentTemperatureLabel, 141);
    lv_obj_set_align(ui_CurrentTemperatureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentTemperatureLabel, "Current temperature: ");
    lv_obj_set_style_text_font(ui_CurrentTemperatureLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentTemperatureValueLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CurrentTemperatureValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentTemperatureValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentTemperatureValueLabel, 140);
    lv_obj_set_y(ui_CurrentTemperatureValueLabel, 141);
    lv_obj_set_align(ui_CurrentTemperatureValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentTemperatureValueLabel, "0");
    lv_obj_set_style_text_font(ui_CurrentTemperatureValueLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TemperatureSlider, ui_event_TemperatureSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DecreaseTemperatureButton, ui_event_DecreaseTemperatureButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IncreaseTemperatureButton, ui_event_IncreaseTemperatureButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsButton, ui_event_SettingsButton, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TemperatureSlider = NULL;
    ui_TemperstureLabel = NULL;
    ui_DecreaseTemperatureButton = NULL;
    ui_DecreaseTemperatureLabel = NULL;
    ui_IncreaseTemperatureButton = NULL;
    ui_IncreaseTemperatureLabel = NULL;
    ui_TabViewPanel = NULL;
    ui_Button4 = NULL;
    ui_Button5 = NULL;
    ui_SettingsButton = NULL;
    ui_SettingsImg = NULL;
    ui_HeatImg = NULL;
    ui_CurrentTemperatureLabel = NULL;
    ui_CurrentTemperatureValueLabel = NULL;

}
