// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Roller2 = NULL;
lv_obj_t * ui_Spinbox1 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Colorwheel1 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_Checkbox1 = NULL;
lv_obj_t * ui_Calendar1 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Button3 = NULL;
// event funtions
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        checked_switch(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        unchecked_switch(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller2 = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_Roller2,
                          "Option 1\nOption 2\nOption 3\nOption 4\nOption 5\nOption 6\nOption 7\nOption 8\nOption 9\nOption 10",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller2, 100);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller2, -171);
    lv_obj_set_y(ui_Roller2, -172);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);

    ui_Spinbox1 = lv_spinbox_create(ui_Screen3);
    lv_obj_set_width(ui_Spinbox1, 70);
    lv_obj_set_height(ui_Spinbox1, 42);
    lv_obj_set_x(ui_Spinbox1, -164);
    lv_obj_set_y(ui_Spinbox1, -21);
    lv_obj_set_align(ui_Spinbox1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox1, 4, 2);
    lv_spinbox_set_range(ui_Spinbox1, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);

    ui_Switch1 = lv_switch_create(ui_Screen3);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -66);
    lv_obj_set_y(ui_Switch1, -198);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Colorwheel1 = lv_colorwheel_create(ui_Screen3, true);
    lv_obj_set_width(ui_Colorwheel1, 150);
    lv_obj_set_height(ui_Colorwheel1, 150);
    lv_obj_set_x(ui_Colorwheel1, 161);
    lv_obj_set_y(ui_Colorwheel1, -162);
    lv_obj_set_align(ui_Colorwheel1, LV_ALIGN_CENTER);

    ui_Slider1 = lv_slider_create(ui_Screen3);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, -140);
    lv_obj_set_y(ui_Slider1, -76);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Dropdown1 = lv_dropdown_create(ui_Screen3);
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -149);
    lv_obj_set_y(ui_Dropdown1, 49);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Checkbox1 = lv_checkbox_create(ui_Screen3);
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox1, -36);
    lv_obj_set_y(ui_Checkbox1, -161);
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Calendar1 = lv_calendar_create(ui_Screen3);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 230);
    lv_obj_set_height(ui_Calendar1, 240);
    lv_obj_set_x(ui_Calendar1, 112);
    lv_obj_set_y(ui_Calendar1, 111);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);

    ui_Bar1 = lv_bar_create(ui_Screen3);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 150);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, -148);
    lv_obj_set_y(ui_Bar1, 117);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_Spinner1 = lv_spinner_create(ui_Screen3, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, -165);
    lv_obj_set_y(ui_Spinner1, 175);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea1, 150);
    lv_obj_set_height(ui_TextArea1, 70);
    lv_obj_set_x(ui_TextArea1, 20);
    lv_obj_set_y(ui_TextArea1, -75);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_Button3 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button3, 50);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -56);
    lv_obj_set_y(ui_Button3, 190);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Roller2 = NULL;
    ui_Spinbox1 = NULL;
    ui_Switch1 = NULL;
    ui_Colorwheel1 = NULL;
    ui_Slider1 = NULL;
    ui_Dropdown1 = NULL;
    ui_Checkbox1 = NULL;
    ui_Calendar1 = NULL;
    ui_Bar1 = NULL;
    ui_Spinner1 = NULL;
    ui_TextArea1 = NULL;
    ui_Button3 = NULL;

}
