// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_TemperatureSlider(lv_event_t * e);
extern lv_obj_t * ui_TemperatureSlider;
extern lv_obj_t * ui_TemperstureLabel;
extern void ui_event_DecreaseTemperatureButton(lv_event_t * e);
extern lv_obj_t * ui_DecreaseTemperatureButton;
extern lv_obj_t * ui_DecreaseTemperatureLabel;
extern void ui_event_IncreaseTemperatureButton(lv_event_t * e);
extern lv_obj_t * ui_IncreaseTemperatureButton;
extern lv_obj_t * ui_IncreaseTemperatureLabel;
extern lv_obj_t * ui_TabViewPanel;
extern lv_obj_t * ui_Button4;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern void ui_event_SettingsButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsButton;
extern lv_obj_t * ui_SettingsImg;
extern lv_obj_t * ui_HeatImg;
extern lv_obj_t * ui_CurrentTemperatureLabel;
extern lv_obj_t * ui_CurrentTemperatureValueLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

